-- Generated by build_data.py
begin;

create table if not exists public.students (
  id text primary key,
  name text not null,
  grade integer not null,
  grade_label text not null,
  class_room integer not null,
  class_label text not null,
  number_label text,
  phone text not null,
  active boolean not null default true
);

create table if not exists public.courses (
  id text primary key,
  name text not null,
  days_json jsonb not null,
  room text,
  location text,
  teacher text,
  teacher_phone text,
  capacity integer,
  fee_type text,
  fee text,
  note text
);

create table if not exists public.course_slots (
  id text primary key,
  course_id text not null references public.courses(id) on delete cascade,
  period text not null,
  start_time text not null,
  end_time text not null,
  grade_min integer not null,
  grade_max integer not null,
  days_json jsonb not null,
  room text,
  location text,
  capacity integer
);

create table if not exists public.applications (
  student_id text not null references public.students(id) on delete cascade,
  slot_id text not null references public.course_slots(id) on delete cascade,
  updated_at timestamptz not null default now(),
  primary key (student_id, slot_id)
);

alter table public.students enable row level security;
alter table public.courses enable row level security;
alter table public.course_slots enable row level security;
alter table public.applications enable row level security;

drop policy if exists deny_all_students on public.students;
drop policy if exists deny_all_courses on public.courses;
drop policy if exists deny_all_course_slots on public.course_slots;
drop policy if exists deny_all_applications on public.applications;

create policy deny_all_students on public.students for all using (false) with check (false);
create policy deny_all_courses on public.courses for all using (false) with check (false);
create policy deny_all_course_slots on public.course_slots for all using (false) with check (false);
create policy deny_all_applications on public.applications for all using (false) with check (false);

truncate table public.applications;
truncate table public.course_slots cascade;
truncate table public.courses cascade;
truncate table public.students cascade;

insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-공도현', '공도현', 1, '1학년', 1, '1반', '', '01034360666', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-구다온', '구다온', 1, '1학년', 1, '1반', '', '01024358412', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-김도윤', '김도윤', 1, '1학년', 1, '1반', '', '01053367920', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-김리훈', '김리훈', 1, '1학년', 1, '1반', '', '01092129364', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-김소유', '김소유', 1, '1학년', 1, '1반', '', '01048075390', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-김지유', '김지유', 1, '1학년', 1, '1반', '', '01022462998', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-나승민', '나승민', 1, '1학년', 1, '1반', '', '01082349960', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-문지훈', '문지훈', 1, '1학년', 1, '1반', '', '01036663892', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-박설아', '박설아', 1, '1학년', 1, '1반', '', '01083698869', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-박시하', '박시하', 1, '1학년', 1, '1반', '', '01062899009', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-박하윤', '박하윤', 1, '1학년', 1, '1반', '', '01096206399', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-박혜미', '박혜미', 1, '1학년', 1, '1반', '', '01094429416', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-안건후', '안건후', 1, '1학년', 1, '1반', '', '01090081507', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-이가혁', '이가혁', 1, '1학년', 1, '1반', '', '01044229008', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-장시원', '장시원', 1, '1학년', 1, '1반', '', '01089519027', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-정하린', '정하린', 1, '1학년', 1, '1반', '', '01066113974', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-최빛나', '최빛나', 1, '1학년', 1, '1반', '', '01026155644', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-황대현', '황대현', 1, '1학년', 1, '1반', '', '01045118006', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-1-황민지', '황민지', 1, '1학년', 1, '1반', '', '01026979192', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-강민성', '강민성', 1, '1학년', 2, '2반', '', '01056859780', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-김가윤', '김가윤', 1, '1학년', 2, '2반', '', '01028596713', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-김민호', '김민호', 1, '1학년', 2, '2반', '', '01071271325', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-김지아', '김지아', 1, '1학년', 2, '2반', '', '01089096230', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-김채원', '김채원', 1, '1학년', 2, '2반', '', '01190999611', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-김하연', '김하연', 1, '1학년', 2, '2반', '', '01036323453', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-나윤우', '나윤우', 1, '1학년', 2, '2반', '', '01041509758', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-박지원', '박지원', 1, '1학년', 2, '2반', '', '01036450150', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-박찬영', '박찬영', 1, '1학년', 2, '2반', '', '01072540511', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-서유림', '서유림', 1, '1학년', 2, '2반', '', '01056148023', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-손가은', '손가은', 1, '1학년', 2, '2반', '', '01064313532', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-신세아', '신세아', 1, '1학년', 2, '2반', '', '01036174460', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-윤새봄', '윤새봄', 1, '1학년', 2, '2반', '', '01020179230', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-이아린', '이아린', 1, '1학년', 2, '2반', '', '01039300537', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-이정민', '이정민', 1, '1학년', 2, '2반', '', '01037458927', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-이지유', '이지유', 1, '1학년', 2, '2반', '', '01050564949', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-정건우', '정건우', 1, '1학년', 2, '2반', '', '01094333574', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('1-2-정영호', '정영호', 1, '1학년', 2, '2반', '', '01095860096', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-강서후', '강서후', 2, '2학년', 1, '1반', '', '01063478543', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-강하리', '강하리', 2, '2학년', 1, '1반', '', '01032115790', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-강하엘', '강하엘', 2, '2학년', 1, '1반', '', '01056764725', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-공예은', '공예은', 2, '2학년', 1, '1반', '', '01096861788', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-김선우', '김선우', 2, '2학년', 1, '1반', '', '01066026705', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-김지현', '김지현', 2, '2학년', 1, '1반', '', '01086128043', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-노빛나라', '노빛나라', 2, '2학년', 1, '1반', '', '01085891595', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-노유진', '노유진', 2, '2학년', 1, '1반', '', '01096369371', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-박도영', '박도영', 2, '2학년', 1, '1반', '', '01046139493', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-박서은', '박서은', 2, '2학년', 1, '1반', '', '01037846399', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-박소유', '박소유', 2, '2학년', 1, '1반', '', '01049017867', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-박지온', '박지온', 2, '2학년', 1, '1반', '', '01077212930', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-박찬호', '박찬호', 2, '2학년', 1, '1반', '', '01026825297', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-유하경', '유하경', 2, '2학년', 1, '1반', '', '01062277064', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-장다율', '장다율', 2, '2학년', 1, '1반', '', '01063671021', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-조중근', '조중근', 2, '2학년', 1, '1반', '', '01036253885', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-한동욱', '한동욱', 2, '2학년', 1, '1반', '', '01083990928', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-1-황수진', '황수진', 2, '2학년', 1, '1반', '', '01036843883', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-김동율', '김동율', 2, '2학년', 2, '2반', '', '01087978255', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-김리온', '김리온', 2, '2학년', 2, '2반', '', '01045555309', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-김미소', '김미소', 2, '2학년', 2, '2반', '', '01087875472', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-김유빈', '김유빈', 2, '2학년', 2, '2반', '', '01095959756', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-김현민', '김현민', 2, '2학년', 2, '2반', '', '01029361232', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-박라엘', '박라엘', 2, '2학년', 2, '2반', '', '01096893309', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-박시영', '박시영', 2, '2학년', 2, '2반', '', '01086985569', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-박은혜', '박은혜', 2, '2학년', 2, '2반', '', '01020301002', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-박지우', '박지우', 2, '2학년', 2, '2반', '', '01094419719', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-베르마손지한', '베르마손지한', 2, '2학년', 2, '2반', '', '01046695625', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-송예담', '송예담', 2, '2학년', 2, '2반', '', '01053889449', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-원민아', '원민아', 2, '2학년', 2, '2반', '', '01072881993', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-원예린', '원예린', 2, '2학년', 2, '2반', '', '01077147035', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-천우진', '천우진', 2, '2학년', 2, '2반', '', '01066646521', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-최아린', '최아린', 2, '2학년', 2, '2반', '', '01086131620', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-최예진', '최예진', 2, '2학년', 2, '2반', '', '01034918041', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-최은우', '최은우', 2, '2학년', 2, '2반', '', '01063259739', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-2-황나윤', '황나윤', 2, '2학년', 2, '2반', '', '01055383344', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-김리하', '김리하', 2, '2학년', 3, '3반', '', '01033728177', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-김수아', '김수아', 2, '2학년', 3, '3반', '', '01029857195', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-김연희', '김연희', 2, '2학년', 3, '3반', '', '01028491430', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-김태이', '김태이', 2, '2학년', 3, '3반', '', '01036050279', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-노승후', '노승후', 2, '2학년', 3, '3반', '', '01089559160', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-박도윤', '박도윤', 2, '2학년', 3, '3반', '', '01082334799', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-박서현', '박서현', 2, '2학년', 3, '3반', '', '01044343244', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-박준서', '박준서', 2, '2학년', 3, '3반', '', '01071689053', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-손도담', '손도담', 2, '2학년', 3, '3반', '', '01041734122', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-손예진', '손예진', 2, '2학년', 3, '3반', '', '01037080913', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-엄태희', '엄태희', 2, '2학년', 3, '3반', '', '01041881130', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-염예원', '염예원', 2, '2학년', 3, '3반', '', '01066200018', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-이로운', '이로운', 2, '2학년', 3, '3반', '', '01080145868', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-전재성', '전재성', 2, '2학년', 3, '3반', '', '01088098937', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-조선우', '조선우', 2, '2학년', 3, '3반', '', '01056676992', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-최정우', '최정우', 2, '2학년', 3, '3반', '', '01035606834', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('2-3-최지호', '최지호', 2, '2학년', 3, '3반', '', '01036200604', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-구하영', '구하영', 3, '3학년', 1, '1반', '', '01041531736', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-김시윤', '김시윤', 3, '3학년', 1, '1반', '', '01026440385', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-김지율', '김지율', 3, '3학년', 1, '1반', '', '01094736844', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-김지한', '김지한', 3, '3학년', 1, '1반', '', '01056802468', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-박상민', '박상민', 3, '3학년', 1, '1반', '', '01094429416', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-박수영', '박수영', 3, '3학년', 1, '1반', '', '01092307400', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-박채론', '박채론', 3, '3학년', 1, '1반', '', '01091613613', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-박하준', '박하준', 3, '3학년', 1, '1반', '', '01063333555', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-윤한울', '윤한울', 3, '3학년', 1, '1반', '', '01076466030', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-이민준', '이민준', 3, '3학년', 1, '1반', '', '01046641754', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-이연우', '이연우', 3, '3학년', 1, '1반', '', '01085650230', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-이영주', '이영주', 3, '3학년', 1, '1반', '', '01076808525', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-이정우', '이정우', 3, '3학년', 1, '1반', '', '01036250753', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-이준우', '이준우', 3, '3학년', 1, '1반', '', '01097983688', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-이한결', '이한결', 3, '3학년', 1, '1반', '', '01062360353', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-장보미', '장보미', 3, '3학년', 1, '1반', '', '01025518588', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-전하미', '전하미', 3, '3학년', 1, '1반', '', '01022863979', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-조성용', '조성용', 3, '3학년', 1, '1반', '', '01094845915', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-주서연', '주서연', 3, '3학년', 1, '1반', '', '01036327579', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-진지성', '진지성', 3, '3학년', 1, '1반', '', '01046200412', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-최수영', '최수영', 3, '3학년', 1, '1반', '', '01036184788', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-현이나', '현이나', 3, '3학년', 1, '1반', '', '01091996713', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-1-황재원', '황재원', 3, '3학년', 1, '1반', '', '01059120814', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-강준우', '강준우', 3, '3학년', 2, '2반', '', '01085478647', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-고현슬', '고현슬', 3, '3학년', 2, '2반', '', '01026763220', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-김민서', '김민서', 3, '3학년', 2, '2반', '', '01041931247', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-김서희', '김서희', 3, '3학년', 2, '2반', '', '01094917920', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-김승현', '김승현', 3, '3학년', 2, '2반', '', '01042068672', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-김태윤', '김태윤', 3, '3학년', 2, '2반', '', '01082401653', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-나윤이', '나윤이', 3, '3학년', 2, '2반', '', '01041509758', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-박은총', '박은총', 3, '3학년', 2, '2반', '', '01020301002', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-박지유', '박지유', 3, '3학년', 2, '2반', '', '01020801370', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-배시현', '배시현', 3, '3학년', 2, '2반', '', '01094428317', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-변우빈', '변우빈', 3, '3학년', 2, '2반', '', '01047667908', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-이서율', '이서율', 3, '3학년', 2, '2반', '', '01092707815', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-이서은', '이서은', 3, '3학년', 2, '2반', '', '01068091158', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-이승혁', '이승혁', 3, '3학년', 2, '2반', '', '01090381196', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-임준열', '임준열', 3, '3학년', 2, '2반', '', '01066457548', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-장재하', '장재하', 3, '3학년', 2, '2반', '', '01086465172', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-정승준', '정승준', 3, '3학년', 2, '2반', '', '01041301245', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-조민건', '조민건', 3, '3학년', 2, '2반', '', '01046101788', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-조민우', '조민우', 3, '3학년', 2, '2반', '', '01066332606', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-조우림', '조우림', 3, '3학년', 2, '2반', '', '01096360402', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-최세하', '최세하', 3, '3학년', 2, '2반', '', '01026667584', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-최지현', '최지현', 3, '3학년', 2, '2반', '', '01039033557', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-황동하', '황동하', 3, '3학년', 2, '2반', '', '01097749666', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('3-2-황지우', '황지우', 3, '3학년', 2, '2반', '', '01092391203', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-김경원', '김경원', 4, '4학년', 1, '1반', '', '01047878689', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-김다온', '김다온', 4, '4학년', 1, '1반', '', '01094328781', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-김선우', '김선우', 4, '4학년', 1, '1반', '', '01020808054', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-김승아', '김승아', 4, '4학년', 1, '1반', '', '01046410215', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-나윤아', '나윤아', 4, '4학년', 1, '1반', '', '01071703768', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-노유민', '노유민', 4, '4학년', 1, '1반', '', '01096369371', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-문주원', '문주원', 4, '4학년', 1, '1반', '', '01046047586', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-민주완', '민주완', 4, '4학년', 1, '1반', '', '01026209337', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-박은빈', '박은빈', 4, '4학년', 1, '1반', '', '01038407733', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-박하희', '박하희', 4, '4학년', 1, '1반', '', '01046320603', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-손예나', '손예나', 4, '4학년', 1, '1반', '', '01041023092', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-송민서', '송민서', 4, '4학년', 1, '1반', '', '01053889449', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-신소율', '신소율', 4, '4학년', 1, '1반', '', '01063451378', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-신지안', '신지안', 4, '4학년', 1, '1반', '', '01086147857', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-안리안', '안리안', 4, '4학년', 1, '1반', '', '01074009620', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-오해인', '오해인', 4, '4학년', 1, '1반', '', '01065600803', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-이다연', '이다연', 4, '4학년', 1, '1반', '', '01045918571', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-이지수', '이지수', 4, '4학년', 1, '1반', '', '01023696900', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-이지윤', '이지윤', 4, '4학년', 1, '1반', '', '01071711630', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-정하준', '정하준', 4, '4학년', 1, '1반', '', '01026421621', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-최슬예', '최슬예', 4, '4학년', 1, '1반', '', '01047801303', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-최시우', '최시우', 4, '4학년', 1, '1반', '', '01027503330', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-하승현', '하승현', 4, '4학년', 1, '1반', '', '01094318122', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-홍예준', '홍예준', 4, '4학년', 1, '1반', '', '01085459759', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-1-홍준영', '홍준영', 4, '4학년', 1, '1반', '', '01048099536', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-고유라', '고유라', 4, '4학년', 2, '2반', '', '01073438870', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-공서빈', '공서빈', 4, '4학년', 2, '2반', '', '01035490888', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-김예준', '김예준', 4, '4학년', 2, '2반', '', '01046149670', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-김채린', '김채린', 4, '4학년', 2, '2반', '', '01039380960', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-노을', '노을', 4, '4학년', 2, '2반', '', '01085891595', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-문서진', '문서진', 4, '4학년', 2, '2반', '', '01052915957', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-박수', '박수', 4, '4학년', 2, '2반', '', '01095110360', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-박예지', '박예지', 4, '4학년', 2, '2반', '', '01020848484', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-선유하', '선유하', 4, '4학년', 2, '2반', '', '01087134677', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-선율', '선율', 4, '4학년', 2, '2반', '', '01031123919', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-송채라', '송채라', 4, '4학년', 2, '2반', '', '01034274567', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-염유안', '염유안', 4, '4학년', 2, '2반', '', '01022324040', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-임윤솔', '임윤솔', 4, '4학년', 2, '2반', '', '01071736643', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-임형우', '임형우', 4, '4학년', 2, '2반', '', '01035004993', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-장서아', '장서아', 4, '4학년', 2, '2반', '', '01087573051', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-전하준', '전하준', 4, '4학년', 2, '2반', '', '01096914012', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-정라율', '정라율', 4, '4학년', 2, '2반', '', '01036403901', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-정수빈', '정수빈', 4, '4학년', 2, '2반', '', '01052367648', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-최범준', '최범준', 4, '4학년', 2, '2반', '', '01026155644', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-최선우', '최선우', 4, '4학년', 2, '2반', '', '01027503330', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-최수진', '최수진', 4, '4학년', 2, '2반', '', '01034918041', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-최지한', '최지한', 4, '4학년', 2, '2반', '', '01086243125', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-최현비', '최현비', 4, '4학년', 2, '2반', '', '01094307280', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-2-황다윤', '황다윤', 4, '4학년', 2, '2반', '', '01022342540', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-공하은', '공하은', 4, '4학년', 3, '3반', '', '01040978967', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-김동빈', '김동빈', 4, '4학년', 3, '3반', '', '01053268255', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-김민준', '김민준', 4, '4학년', 3, '3반', '', '01020155926', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-김정원', '김정원', 4, '4학년', 3, '3반', '', '01089096230', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-나규빈', '나규빈', 4, '4학년', 3, '3반', '', '01086226752', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-박서우', '박서우', 4, '4학년', 3, '3반', '', '01049326107', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-박선유', '박선유', 4, '4학년', 3, '3반', '', '01035329347', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-박연우', '박연우', 4, '4학년', 3, '3반', '', '01094419719', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-박하엘', '박하엘', 4, '4학년', 3, '3반', '', '01092146286', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-백혜원', '백혜원', 4, '4학년', 3, '3반', '', '01066790036', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-안유안', '안유안', 4, '4학년', 3, '3반', '', '01074009620', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-유태훈', '유태훈', 4, '4학년', 3, '3반', '', '01088473794', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-윤건우', '윤건우', 4, '4학년', 3, '3반', '', '01050557175', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-이규비', '이규비', 4, '4학년', 3, '3반', '', '01063784190', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-이다은', '이다은', 4, '4학년', 3, '3반', '', '01068091158', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-이주원', '이주원', 4, '4학년', 3, '3반', '', '01028297059', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-이지우', '이지우', 4, '4학년', 3, '3반', '', '01066605078', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-이채원', '이채원', 4, '4학년', 3, '3반', '', '01059406176', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-전지유', '전지유', 4, '4학년', 3, '3반', '', '01088762211', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-전하린', '전하린', 4, '4학년', 3, '3반', '', '01099278502', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-정다빈', '정다빈', 4, '4학년', 3, '3반', '', '01052367648', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-정윤서', '정윤서', 4, '4학년', 3, '3반', '', '01022279288', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-편소율', '편소율', 4, '4학년', 3, '3반', '', '01055270144', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-한서준', '한서준', 4, '4학년', 3, '3반', '', '01057189364', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('4-3-허재준', '허재준', 4, '4학년', 3, '3반', '', '01097320323', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김나루', '김나루', 5, '5학년', 1, '1반', '', '01072940068', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김도원', '김도원', 5, '5학년', 1, '1반', '', '01084815666', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김선희', '김선희', 5, '5학년', 1, '1반', '', '01048186671', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김소현', '김소현', 5, '5학년', 1, '1반', '', '01096881511', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김수인', '김수인', 5, '5학년', 1, '1반', '', '01051435143', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김시원', '김시원', 5, '5학년', 1, '1반', '', '01096290929', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김종범', '김종범', 5, '5학년', 1, '1반', '', '01088998844', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-김지민', '김지민', 5, '5학년', 1, '1반', '', '01034850189', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-나수환', '나수환', 5, '5학년', 1, '1반', '', '01046226898', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-민태오', '민태오', 5, '5학년', 1, '1반', '', '01021889173', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-박다솜', '박다솜', 5, '5학년', 1, '1반', '', '01030394117', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-박서현', '박서현', 5, '5학년', 1, '1반', '', '01055088226', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-박현결', '박현결', 5, '5학년', 1, '1반', '', '01093293254', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-신가람', '신가람', 5, '5학년', 1, '1반', '', '01097651027', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-안도현', '안도현', 5, '5학년', 1, '1반', '', '01020218962', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-안민준', '안민준', 5, '5학년', 1, '1반', '', '01090081507', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-오지홍', '오지홍', 5, '5학년', 1, '1반', '', '01065600803', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-이경희', '이경희', 5, '5학년', 1, '1반', '', '01030088532', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-이민호', '이민호', 5, '5학년', 1, '1반', '', '01073446789', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-임유린', '임유린', 5, '5학년', 1, '1반', '', '01087669264', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-장다은', '장다은', 5, '5학년', 1, '1반', '', '01051303833', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-정화율', '정화율', 5, '5학년', 1, '1반', '', '01036181659', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-조서빈', '조서빈', 5, '5학년', 1, '1반', '', '01089638186', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-최은서', '최은서', 5, '5학년', 1, '1반', '', '01063259739', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-1-한승우', '한승우', 5, '5학년', 1, '1반', '', '01066426014', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-고연우', '고연우', 5, '5학년', 2, '2반', '', '01026763220', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-김산유', '김산유', 5, '5학년', 2, '2반', '', '01086088310', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-김성은', '김성은', 5, '5학년', 2, '2반', '', '01075398007', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-김소연', '김소연', 5, '5학년', 2, '2반', '', '01066345768', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-김희서', '김희서', 5, '5학년', 2, '2반', '', '01033728177', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-노영우', '노영우', 5, '5학년', 2, '2반', '', '01021707488', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-민태이', '민태이', 5, '5학년', 2, '2반', '', '01021889173', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박샤인', '박샤인', 5, '5학년', 2, '2반', '', '01082650718', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박소민', '박소민', 5, '5학년', 2, '2반', '', '01090697861', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박영재', '박영재', 5, '5학년', 2, '2반', '', '01077120600', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박의준', '박의준', 5, '5학년', 2, '2반', '', '01096893309', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박지환', '박지환', 5, '5학년', 2, '2반', '', '01020801370', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박찬우', '박찬우', 5, '5학년', 2, '2반', '', '01022982298', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-박찬혁', '박찬혁', 5, '5학년', 2, '2반', '', '01051310255', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-백윤서', '백윤서', 5, '5학년', 2, '2반', '', '01094338895', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-엄주희', '엄주희', 5, '5학년', 2, '2반', '', '01097403808', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-이다은', '이다은', 5, '5학년', 2, '2반', '', '01039501106', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-이준형', '이준형', 5, '5학년', 2, '2반', '', '01066546301', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-장한결', '장한결', 5, '5학년', 2, '2반', '', '01050657649', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-정세영', '정세영', 5, '5학년', 2, '2반', '', '01093641228', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-주준혁', '주준혁', 5, '5학년', 2, '2반', '', '01079380424', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-진지호', '진지호', 5, '5학년', 2, '2반', '', '01020402700', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-최소희', '최소희', 5, '5학년', 2, '2반', '', '01031627633', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-2-황다연', '황다연', 5, '5학년', 2, '2반', '', '01096887627', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김가원', '김가원', 5, '5학년', 3, '3반', '', '01071271325', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김다윤', '김다윤', 5, '5학년', 3, '3반', '', '01030744622', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김다효', '김다효', 5, '5학년', 3, '3반', '', '01040550072', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김도운', '김도운', 5, '5학년', 3, '3반', '', '01095006023', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김라희', '김라희', 5, '5학년', 3, '3반', '', '01025176099', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김려륜', '김려륜', 5, '5학년', 3, '3반', '', '01045429014', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김민기', '김민기', 5, '5학년', 3, '3반', '', '01041931247', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김연재', '김연재', 5, '5학년', 3, '3반', '', '01028491430', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-김예찬', '김예찬', 5, '5학년', 3, '3반', '', '01046149670', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-나유찬', '나유찬', 5, '5학년', 3, '3반', '', '01026053626', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-박민준', '박민준', 5, '5학년', 3, '3반', '', '01062736399', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-유소명', '유소명', 5, '5학년', 3, '3반', '', '01082472336', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-이경준', '이경준', 5, '5학년', 3, '3반', '', '01046641754', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-이서윤', '이서윤', 5, '5학년', 3, '3반', '', '01046630916', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-임설아', '임설아', 5, '5학년', 3, '3반', '', '01038375466', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-정태민', '정태민', 5, '5학년', 3, '3반', '', '01036419967', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-조나현', '조나현', 5, '5학년', 3, '3반', '', '01052886460', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-조아현', '조아현', 5, '5학년', 3, '3반', '', '01062817740', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-조예담', '조예담', 5, '5학년', 3, '3반', '', '01083301914', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-최승우', '최승우', 5, '5학년', 3, '3반', '', '01071098434', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-하성우', '하성우', 5, '5학년', 3, '3반', '', '01071764217', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-홍은서', '홍은서', 5, '5학년', 3, '3반', '', '01064622653', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('5-3-황다인', '황다인', 5, '5학년', 3, '3반', '', '01086103507', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-강소희', '강소희', 6, '6학년', 1, '1반', '', '01093678189', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-강희성', '강희성', 6, '6학년', 1, '1반', '', '01049367386', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김나연', '김나연', 6, '6학년', 1, '1반', '', '01034243161', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김미소', '김미소', 6, '6학년', 1, '1반', '', '01062523249', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김성대', '김성대', 6, '6학년', 1, '1반', '', '01075398007', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김시헌', '김시헌', 6, '6학년', 1, '1반', '', '01026150002', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김신선', '김신선', 6, '6학년', 1, '1반', '', '01063453989', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김여진', '김여진', 6, '6학년', 1, '1반', '', '01085345375', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김정민', '김정민', 6, '6학년', 1, '1반', '', '01040199829', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-김준혁', '김준혁', 6, '6학년', 1, '1반', '', '01047878689', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-나윤서', '나윤서', 6, '6학년', 1, '1반', '', '01071703768', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-박지우', '박지우', 6, '6학년', 1, '1반', '', '01049326107', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-박진', '박진', 6, '6학년', 1, '1반', '', '01092190352', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-박태영', '박태영', 6, '6학년', 1, '1반', '', '01046139493', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-박하이', '박하이', 6, '6학년', 1, '1반', '', '01095110360', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-빙윤하', '빙윤하', 6, '6학년', 1, '1반', '', '01094963104', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-손예린', '손예린', 6, '6학년', 1, '1반', '', '01041023092', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-유하원', '유하원', 6, '6학년', 1, '1반', '', '01076831198', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-이승현', '이승현', 6, '6학년', 1, '1반', '', '01062620313', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-임하율', '임하율', 6, '6학년', 1, '1반', '', '01038375466', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-정시우', '정시우', 6, '6학년', 1, '1반', '', '01037540893', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-최지후', '최지후', 6, '6학년', 1, '1반', '', '01086243125', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-1-하준석', '하준석', 6, '6학년', 1, '1반', '', '01094318122', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-구하은', '구하은', 6, '6학년', 2, '2반', '', '01062608013', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-김라온', '김라온', 6, '6학년', 2, '2반', '', '01094328781', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-김성연', '김성연', 6, '6학년', 2, '2반', '', '01035103292', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-김현진', '김현진', 6, '6학년', 2, '2반', '', '01094655297', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-김환희', '김환희', 6, '6학년', 2, '2반', '', '01029311070', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-나승준', '나승준', 6, '6학년', 2, '2반', '', '01055968943', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-민주성', '민주성', 6, '6학년', 2, '2반', '', '01088658600', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-박수인', '박수인', 6, '6학년', 2, '2반', '', '01037737929', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-박하준', '박하준', 6, '6학년', 2, '2반', '', '01092146286', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-서진우', '서진우', 6, '6학년', 2, '2반', '', '01052537987', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-송유라', '송유라', 6, '6학년', 2, '2반', '', '01034274567', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-신태훈', '신태훈', 6, '6학년', 2, '2반', '', '01089200344', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-신하율', '신하율', 6, '6학년', 2, '2반', '', '01063451378', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-유윤서', '유윤서', 6, '6학년', 2, '2반', '', '01029270543', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-윤예인', '윤예인', 6, '6학년', 2, '2반', '', '01064386954', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-이은솔', '이은솔', 6, '6학년', 2, '2반', '', '01026458720', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-임찬열', '임찬열', 6, '6학년', 2, '2반', '', '01066457548', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-전하민', '전하민', 6, '6학년', 2, '2반', '', '01096914012', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-정주희', '정주희', 6, '6학년', 2, '2반', '', '01046448802', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-최다솜', '최다솜', 6, '6학년', 2, '2반', '', '01089040117', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-최수연', '최수연', 6, '6학년', 2, '2반', '', '01047801303', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-편소이', '편소이', 6, '6학년', 2, '2반', '', '01055270144', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-하소희', '하소희', 6, '6학년', 2, '2반', '', '01071764217', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-2-황서윤', '황서윤', 6, '6학년', 2, '2반', '', '01022342540', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김담우', '김담우', 6, '6학년', 3, '3반', '', '01028698379', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김도윤', '김도윤', 6, '6학년', 3, '3반', '', '01020257465', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김동윤', '김동윤', 6, '6학년', 3, '3반', '', '01053268255', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김민수', '김민수', 6, '6학년', 3, '3반', '', '01082567907', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김수연', '김수연', 6, '6학년', 3, '3반', '', '01046899689', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김승현', '김승현', 6, '6학년', 3, '3반', '', '01020844072', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김연아', '김연아', 6, '6학년', 3, '3반', '', '01066751430', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김예슬', '김예슬', 6, '6학년', 3, '3반', '', '01099881631', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김유리', '김유리', 6, '6학년', 3, '3반', '', '01030745927', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김유주', '김유주', 6, '6학년', 3, '3반', '', '01030745927', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김윤준', '김윤준', 6, '6학년', 3, '3반', '', '01075695791', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-김하은', '김하은', 6, '6학년', 3, '3반', '', '01085502809', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-노을빛', '노을빛', 6, '6학년', 3, '3반', '', '01085891595', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-문서영', '문서영', 6, '6학년', 3, '3반', '', '01052915957', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-박민채', '박민채', 6, '6학년', 3, '3반', '', '01035329347', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-신강호', '신강호', 6, '6학년', 3, '3반', '', '01033722417', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-엄준', '엄준', 6, '6학년', 3, '3반', '', '01097403808', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-윤성빈', '윤성빈', 6, '6학년', 3, '3반', '', '01044319192', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-윤아람', '윤아람', 6, '6학년', 3, '3반', '', '01036321467', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-이다원', '이다원', 6, '6학년', 3, '3반', '', '01028297059', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-이초비', '이초비', 6, '6학년', 3, '3반', '', '01071138070', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-정하율', '정하율', 6, '6학년', 3, '3반', '', '01037581364', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-조규진', '조규진', 6, '6학년', 3, '3반', '', '01085823281', true);
insert into public.students (id, name, grade, grade_label, class_room, class_label, number_label, phone, active) values ('6-3-한수진', '한수진', 6, '6학년', 3, '3반', '', '01057189364', true);

insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('creative-art', '창의미술', '["화", "금"]'::jsonb, '별관1실', '별관 2층', '임형은', '010-7765-2870', 20, '수익자', '35,000원', '매월 10,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('creative-robot', '창의로봇', '["화", "금"]'::jsonb, '별관3실', '별관 2층', '서원희', '010-2661-0362', 20, '수익자', '35,000원', '재료비 수준별 88,000~99,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('computer', '컴퓨터', '["월", "목"]'::jsonb, '컴퓨터실', '본관 2층', '홍설희', '010-2890-8683', 25, '수익자', '35,000원', '교재비 수준별 12,000~18,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('abacus', '주산', '["월", "목"]'::jsonb, '별관3실', '별관 2층', '김경매', '010-6406-5336', 20, '수익자', '35,000원', '주판 13,000원, 교재비 수준별 8,000~11,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('hanja', '한자', '["월", "금"]'::jsonb, '상상이룸실', '본관 1층', '심희숙', '010-5581-6733', 20, '수익자', '35,000원', '교재비 수준별 12,000~16,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('piano', '피아노', '["화", "금"]'::jsonb, '별관2실', '별관 2층', '강민정', '010-6800-4233', 14, '무료', '무료', '교재비 수준별 5,000~8,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('violin', '바이올린', '["화", "금"]'::jsonb, '별관2실', '별관 2층', '김규리', '010-4180-9863', 12, '무료', '무료', '교재비 수준별 4,000~12,000원');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('jump-rope', '줄넘기', '["월", "목"]'::jsonb, '호연관', '-', '강선영', '010-8512-4770', 20, '무료', '무료', '개인 줄넘기, 운동화, 물병 준비');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('table-tennis', '탁구', '["화", "금"]'::jsonb, '금성관', '-', '이지우', '010-8603-0030', 12, '무료', '무료', '맞춤형 프로그램');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('dance', '방송댄스', '["월", "목"]'::jsonb, '무용실', '본관 2층', '주연지', '010-8200-2978', 20, '무료', '무료', '2부 무용실 운영');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('new-sports', '뉴스포츠', '["금"]'::jsonb, '호연관', '-', '박종현', '010-5047-3281', 20, '무료', '무료', '금요일 단일 운영');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('book-play', '책놀이', '["월", "목"]'::jsonb, '도서관', '본관 2층', '이향현', '010-8604-3197', 15, '무료', '무료', '도서관 운영');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('math-play', '놀이수학', '["월", "목"]'::jsonb, '교담수업실 2', '본관 2층', '최나라', '010-3163-7227', 16, '무료', '무료', '맞춤형 프로그램');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('jamjam-english', '잼잼잉글리쉬', '["화", "금"]'::jsonb, '교담수업실 1', '본관 3층', '김효빈 / 이지영', '010-8001-3655 / 010-4823-6104', 16, '무료', '무료', '2부 교담수업실 1, 3부 북카페 운영');
insert into public.courses (id, name, days_json, room, location, teacher, teacher_phone, capacity, fee_type, fee, note) values ('play-physical', '놀이체육', '["수"]'::jsonb, '놀이활동실', '본관 3층', '박종현', '010-5047-3281', 18, '무료', '무료', '수요일 단일 운영');

insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('creative-art::2부', 'creative-art', '2부', '14:10', '14:50', 1, 4, '["화", "금"]'::jsonb, '별관1실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('creative-art::3부', 'creative-art', '3부', '14:55', '15:35', 1, 6, '["화", "금"]'::jsonb, '별관1실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('creative-art::4부', 'creative-art', '4부', '15:40', '16:20', 1, 6, '["화", "금"]'::jsonb, '별관1실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('creative-robot::2부', 'creative-robot', '2부', '14:10', '14:50', 1, 4, '["화", "금"]'::jsonb, '별관3실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('creative-robot::3부', 'creative-robot', '3부', '14:55', '15:35', 1, 6, '["화", "금"]'::jsonb, '별관3실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('creative-robot::4부', 'creative-robot', '4부', '15:40', '16:20', 1, 6, '["화", "금"]'::jsonb, '별관3실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('computer::1부', 'computer', '1부', '13:25', '14:05', 1, 2, '["월", "목"]'::jsonb, '컴퓨터실', '본관 2층', 25);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('computer::2부', 'computer', '2부', '14:10', '14:50', 3, 4, '["월", "목"]'::jsonb, '컴퓨터실', '본관 2층', 25);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('computer::3부', 'computer', '3부', '14:55', '15:35', 1, 6, '["월", "목"]'::jsonb, '컴퓨터실', '본관 2층', 25);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('abacus::1부', 'abacus', '1부', '13:25', '14:05', 1, 2, '["월", "목"]'::jsonb, '별관3실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('abacus::2부', 'abacus', '2부', '14:10', '14:50', 1, 4, '["월", "목"]'::jsonb, '별관3실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('abacus::3부', 'abacus', '3부', '14:55', '15:35', 1, 6, '["월", "목"]'::jsonb, '별관3실', '별관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('hanja::2부', 'hanja', '2부', '14:10', '14:50', 1, 4, '["월", "금"]'::jsonb, '상상이룸실', '본관 1층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('hanja::3부', 'hanja', '3부', '14:55', '15:35', 1, 6, '["월", "금"]'::jsonb, '상상이룸실', '본관 1층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('hanja::4부', 'hanja', '4부', '15:40', '16:20', 1, 6, '["월", "금"]'::jsonb, '상상이룸실', '본관 1층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('piano::2부', 'piano', '2부', '14:10', '14:50', 1, 4, '["화", "금"]'::jsonb, '별관2실', '별관 2층', 14);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('piano::3부', 'piano', '3부', '14:55', '15:35', 1, 6, '["화", "금"]'::jsonb, '별관2실', '별관 2층', 14);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('piano::4부', 'piano', '4부', '15:40', '16:20', 1, 6, '["화", "금"]'::jsonb, '별관2실', '별관 2층', 14);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('violin::2부', 'violin', '2부', '14:10', '14:50', 1, 4, '["화", "금"]'::jsonb, '별관2실', '별관 2층', 12);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('violin::3부', 'violin', '3부', '14:55', '15:35', 1, 6, '["화", "금"]'::jsonb, '별관2실', '별관 2층', 12);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('jump-rope::1부', 'jump-rope', '1부', '13:25', '14:05', 1, 2, '["월", "목"]'::jsonb, '호연관', '-', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('jump-rope::2부', 'jump-rope', '2부', '14:10', '14:50', 1, 4, '["월", "목"]'::jsonb, '호연관', '-', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('jump-rope::3부', 'jump-rope', '3부', '14:55', '15:35', 1, 6, '["월", "목"]'::jsonb, '호연관', '-', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('table-tennis::2부', 'table-tennis', '2부', '14:10', '14:50', 1, 4, '["화", "금"]'::jsonb, '금성관', '-', 12);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('table-tennis::3부', 'table-tennis', '3부', '14:55', '15:35', 1, 6, '["화", "금"]'::jsonb, '금성관', '-', 12);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('dance::2부', 'dance', '2부', '14:10', '14:50', 1, 2, '["월", "목"]'::jsonb, '무용실', '본관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('dance::3부', 'dance', '3부', '14:55', '15:35', 3, 6, '["월", "목"]'::jsonb, '무용실', '본관 2층', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('new-sports::2부', 'new-sports', '2부', '14:10', '14:50', 3, 4, '["금"]'::jsonb, '호연관', '-', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('new-sports::3부', 'new-sports', '3부', '14:55', '15:35', 5, 6, '["금"]'::jsonb, '호연관', '-', 20);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('book-play::1부', 'book-play', '1부', '13:25', '14:05', 1, 2, '["월", "목"]'::jsonb, '도서관', '본관 2층', 15);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('book-play::2부', 'book-play', '2부', '14:10', '14:50', 3, 4, '["월", "목"]'::jsonb, '도서관', '본관 2층', 15);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('book-play::3부', 'book-play', '3부', '14:55', '15:35', 5, 6, '["월", "목"]'::jsonb, '도서관', '본관 2층', 15);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('math-play::2부', 'math-play', '2부', '14:10', '14:50', 1, 2, '["월", "목"]'::jsonb, '교담수업실 2', '본관 2층', 16);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('jamjam-english::2부', 'jamjam-english', '2부', '14:10', '14:50', 1, 2, '["화", "금"]'::jsonb, '교담수업실 1', '본관 3층', 16);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('jamjam-english::3부', 'jamjam-english', '3부', '14:55', '15:35', 1, 2, '["화", "금"]'::jsonb, '북카페', '본관 3층', 16);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('play-physical::2부', 'play-physical', '2부', '14:10', '14:50', 1, 2, '["수"]'::jsonb, '놀이활동실', '본관 3층', 18);
insert into public.course_slots (id, course_id, period, start_time, end_time, grade_min, grade_max, days_json, room, location, capacity) values ('play-physical::3부', 'play-physical', '3부', '14:55', '15:35', 1, 2, '["수"]'::jsonb, '놀이활동실', '본관 3층', 18);

commit;
